version: "3.8"

services:
  auth-server:
    build: .
    container_name: auth_dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Mount the current directory into the container
      - ~/.m2:/root/.m2  # Cache Maven dependencies
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
