package org.batuhankertmen.oauthserver.common;

public enum Error {
    INVALID_REQUEST,
    INVALID_CLIENT,
    INVALID_GRANT,
    INVALID_SCOPE,
    INVALID_CODE_CHALLENGE_METHOD,
    CODE_CHALLENGE_MISSING,
    UNAUTHORIZED_CLIENT,
    UNSUPPORTED_GRANT_TYPE,

    INTERNAL_SERVER_ERROR,
    USERNAME_ALREADY_EXISTS,
    CONTACT_ALREADY_EXISTS,
    NOT_FOUND,
    UNAUTHORIZED_USER,
    INVALID_SESSION
}
